### ISSUE TITLE
Missing meta files

### ISSUE THREAD

**Issue by matrosGS** [matt123miller/-VERY-DEPRECATED-VRStarterKit#1]
Can you set in the Edit - Project Settings - Editor: 
Version Control mode: Visible Meta Files
Asset Serialization mode: Force Text

And push Project Settings folder too? 

Otherwise all the references in the scene are missing. 
Thanks.

**Comment by matt123miller** [comment]
Huh, I didn't notice! This repo was made before I knew how to git properly. I'll update this in a few hours.

**Comment by matt123miller** [comment]
So this repo is mostly based around the CardboardControls+ asset found here https://www.assetstore.unity3d.com/en/#!/content/25243 and writing some code to help me use it in useful ways. Because I've fallen far behind where CardboardControls+ is I'm going to mark this repo as deprecated. Feel free to steal the contents of the Classes folder.

**Comment by matrosGS** [comment]
@matt123miller 
I see. Thanks for the response.
